/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dj_jni_jnimodule_NativeHelper */

#ifndef _Included_com_dj_jni_jnimodule_NativeHelper
#define _Included_com_dj_jni_jnimodule_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dj_jni_jnimodule_NativeHelper
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dj_jni_jnimodule_NativeHelper_getStringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
